### PR TITLE
Added texture variable in ItemComponent component in order for invent…

### PR DESCRIPTION
**Pull request by JTrenerry**
Added a texture to the ItemComponent class in order for the Inventory tool to display the correct image easier

### CODE REVIEW

**Comment by JTrenerry** [comment]
Most recent commit isn't in yet one sec!

**Review by p-lahanas — APPROVED** [review]
Tristan happy now

**Review by LiamAnd — APPROVED** [review]
very good

**Review by cmp6 — APPROVED** [review]
should be good

**Review by tristanduncombe — APPROVED** [review]
Looks good

**Pull request merged**
