### PR TITLE
243 inventory toolbar display refresh causing significant lag

### PR DESCRIPTION
**Pull request by tristanduncombe**
Resolve inventory lag issues, and simplify render stage for inventory and toolbar. Has been tested, let me know if there are any unusual bugs.

### CODE REVIEW

**Comment by 86LAK** [comment]
Resolve the conflicts 🙏 then i have a look 👍

**Comment by tristanduncombe** [comment]
> Resolve the conflicts 🙏 then i have a look 👍

Already done :)

**Review by 86LAK — APPROVED** [review]
Tested it in game by spawning all the tools on one tile. Works beautifully :). Didnt stutter or anything. 
code lgtm as well. 

👍 👍 👍 👍 🦖 👍 👍 👍 👍

**Comment by JTrenerry** [comment]
Didn't end up changing Inventory comp?

**Comment by JTrenerry** [comment]
Inventory component also unchanged, what does that mean I need save? the 2 hashs and one array?

**Comment by tristanduncombe** [comment]
> Didn't end up changing item comp?

This is another ticket and not in this issue, it'll be merged in a couple of days

**Review by JTrenerry — APPROVED** [review]
LGTM

**Review by lucashicks1 — APPROVED** [review]
Code LGTM, inventory display is buttery smooth. Well done

**Comment by adamFittlerUQ** [comment]
LGTM Great job man!!!

**Review by adamFittlerUQ — APPROVED** [review]
LGTM

**Pull request merged**
