### PR TITLE
Increase firefly code coverage

### PR DESCRIPTION
**Pull request by JTrenerry**
Helps with #615, increase firefly code coverage by making or improving tests.

### CODE REVIEW

**Comment by JTrenerry** [comment]
Sorry about above commits, the test passed when ran individually but failed in clean build, so I fixed that then it was the other way, so I fixed that, and it flipped again, but is no working.

**Review by 86LAK — CHANGES_REQUESTED** [review]
My code is so bad wtf was i writing

**Comment by JTrenerry** [comment]
> I feel like you could add more things.

This should make firefly code have 100% coverage

**Comment by 86LAK** [comment]
Interesting. how many code smells does it add ?

**Comment by JTrenerry** [comment]
> Interesting. how many code smells does it add ?

unlike your code 0

**Review by 86LAK — APPROVED** [review]
lgtm

**Pull request merged**
