### PR TITLE
More test cases

### PR DESCRIPTION
**Pull request by JTrenerry**
More test cases for SaveGame and SaveLoadService, also implements weather saving.

### CODE REVIEW

**Review by lucashicks1 — APPROVED** [review]
These getters for weather look fine to me :) Thank you

**Comment by 86LAK** [comment]
> > LGTM. but why commit saveFile,json. Maybe remove before we commit., Should probs add to gitignore ?
> 
> Could we even have some test save files that everyone can load in to easily test certain conditions? Like starting off the game with a bunch of plants, tractor!!! and other items??

Yeh this the reason why the saveFile isn't obfuscated. Ig we can create some generic test cases or something in the files and store somewhere. Definetly a good idea

**Comment by JTrenerry** [comment]
bruh this was my reasoning to have it still there, you didn't listen :(. Also just wanted to commit it everytime we made significant changes to the structure so read/debuging would be easier.

**Comment by 86LAK** [comment]
if we leave a suite of test cases we should amend it with this PR and just chuck a few situations in then.

**Review by 86LAK — APPROVED** [review]
lGTM

**Pull request merged**
