### PR TITLE
Mouse Enhancements And Fixes

### PR DESCRIPTION
**Pull request by 86LAK**
FOr task #311 
Quality of life improvements to the mouse feature of the game. Adds yellow square highlighting to the currently in danger tile.

### CODE REVIEW

**Review by JTrenerry — APPROVED** [review]
LGTM

**Comment by JTrenerry** [comment]
Also, was better mouse movement already in main?

**Comment by 86LAK** [comment]
Edited the PR statement to not mention the accuracy fix. You are correct I made a PR into main for that already.

**Comment by JTrenerry** [comment]
> Edited the PR statement to not mention the accuracy fix. You are correct I made a PR into main for that already.

lowkey did not read it and was just asking lol

**Pull request merged**
