### PR TITLE
Code real smelly

### PR DESCRIPTION
**Pull request by lucashicks1**
Makes code a bit less smelly and fixes Jaleel name

### CODE REVIEW

**Review by lucashicks1 — COMMENTED** [review]
I think it looks amazing

**Comment by lucashicks1** [comment]
Who needs a approver?

**Comment by JTrenerry** [comment]
man did easiest smells and called it a day

**Comment by JTrenerry** [comment]
man did easiest smells and called it a day

**Comment by lucashicks1** [comment]
> man did easiest smells and called it a day

You think I'm gonna do the hard ones? I don't want to burn out in sprint 5, saving myself for sprint 6

**Pull request merged**
