### PR TITLE
added game logo

### PR DESCRIPTION
**Pull request by bunnyycat**

### CODE REVIEW

**Comment by vilnor** [comment]
should be able to change the images in `source/core/src/main/com/csse3200/game/utils/DiscordActivity.java` to this

**Comment by JTrenerry** [comment]
> should be able to change the images in `source/core/src/main/com/csse3200/game/utils/DiscordActivity.java` to this
> 
> and if you add some different sizes also the ones in `source/desktop/src/com/csse3200/game/desktop/DesktopLauncher.java`

Only one size is needed technically, it's just for linux and mac users

**Comment by vilnor** [comment]
> > should be able to change the images in `source/core/src/main/com/csse3200/game/utils/DiscordActivity.java` to this
> > and if you add some different sizes also the ones in `source/desktop/src/com/csse3200/game/desktop/DesktopLauncher.java`
> 
> Only one size is needed technically, it's just for linux and mac users

luckily t2 member @yetanothercarbot is using linux and will absolutely bug us about this 🤣

**Review by tristanduncombe — APPROVED** [review]
LGTM, I'll do the discord implementation later tonight!

**Review by JTrenerry — APPROVED** [review]

**Pull request merged**
